name: Update ERDDAP GeoJSON

on:
  schedule:
    - cron: '30 4 * * *'  # 12:30 AM AST / 4:30 AM UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run ERDDAP fetch script
        run: python scripts/erddap_fetch.py

      - name: Commit and push each GeoJSON file with retry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          for file in data/*.geojson; do
            echo "🔄 Attempting to commit and push $file"
            git add "$file"
            git commit -m "🔄 Auto-update ${file##*/}" || echo "No changes for $file"

            success=false
            for attempt in 1 2 3; do
              echo "🚀 Push attempt $attempt for $file"
              if git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}; then
                echo "✅ Successfully pushed $file"
                success=true
                break
              else
                echo "⚠️ Push failed for $file (attempt $attempt)"
                sleep 5
              fi
            done

            if [ "$success" = false ]; then
              echo "❌ Failed to push $file after 3 attempts"
            fi
          done

