name: Update ERDDAP GeoJSON

on:
  schedule:
    - cron: '30 4 * * *'  # 12:30 AM AST / 4:30 AM UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run ERDDAP fetch script
        run: python scripts/erddap_fetch.py

      - name: Commit and push updated GeoJSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Auto-update GeoJSON from ERDDAP"
          file_pattern: data/*.geojson
          commit_user_name: github-actions
          commit_user_email: github-actions@users.noreply.github.com
